-module('Tianjiupai.PlazaServer').
-export(['start_link'/0, 'as_pid'/1, 'get_all_rooms'/0, 'update_room'/1, 'delete_room_sync'/1, 'subscribe'/2, 'unsubscribe'/1]).
'start_link'() -> 'Tianjiupai.PlazaServer.Impl':'start_link_name'(ok, {'global', ok}).
'as_pid'(S1496Proc) -> 'Tianjiupai.PlazaServer.Impl':'as_pid'(S1496Proc).
'get_all_rooms'() -> begin {'ok', S1498Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), begin S1499Res = 'Tianjiupai.PlazaServer.Impl':'call'(S1498Proc, 'get_room_list'), case S1499Res of {'ok', {'room_list_got', S1500RoomSummaries}} -> sesterl_internal_prim:'return'(S1500RoomSummaries); {'error', _} -> sesterl_internal_prim:'return'([]) end end end.
'update_room'(S1502RoomSummary) -> begin {'ok', S1503Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1503Proc, {'update_room', S1502RoomSummary}) end.
'delete_room_sync'(S1505RoomId) -> begin {'ok', S1506Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), begin S1507Res = 'Tianjiupai.PlazaServer.Impl':'call'(S1506Proc, {'delete_room_sync', S1505RoomId}), case S1507Res of {'ok', 'room_deleted'} -> begin _ = begin S3210 = 'Tianjiupai.Logger':'debug'({"room deleted (room_id: ~s)", 1}, {S1505RoomId}), S3210(<<"PlazaServer.sest">>, 301) end, sesterl_internal_prim:'return'(ok) end; {'error', S1508Err} -> begin _ = begin S3211 = 'Tianjiupai.Logger':'warning'({"delete room failed (room_id: ~s, reason: ~p)", 2}, {S1505RoomId, S1508Err}), S3211(<<"PlazaServer.sest">>, 305) end, sesterl_internal_prim:'return'(ok) end end end end.
'subscribe'(S1510UserId, S1511WsProc) -> begin {'ok', S1512Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1512Proc, {'subscribe', S1510UserId, S1511WsProc}) end.
'unsubscribe'(S1514UserId) -> begin {'ok', S1515Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1515Proc, {'unsubscribe', S1514UserId}) end.
