-module('Tianjiupai.Sup.Callback').
-export(['start_room_server_sup'/0, 'start_user_server_sup'/0, 'start_plaza_server'/0, 'start_room_resource_server'/0, 'start_user_resource_server'/0, 'start_metrics_server'/0, 'init'/1]).
'start_room_server_sup'() -> 'SesterlStdlib.SupervisorStatic':'make_child_proc'(fun() -> begin S2897Res = 'Tianjiupai.RoomServerSup':'start_link'(), sesterl_internal_prim:'return'('SesterlStdlib.Result':'map'((fun 'Tianjiupai.RoomServerSup':'as_pid'/1), S2897Res)) end end).
'start_user_server_sup'() -> 'SesterlStdlib.SupervisorStatic':'make_child_proc'(fun() -> begin S2899Res = 'Tianjiupai.UserServerSup':'start_link'(), sesterl_internal_prim:'return'('SesterlStdlib.Result':'map'((fun 'Tianjiupai.UserServerSup':'as_pid'/1), S2899Res)) end end).
'start_plaza_server'() -> 'SesterlStdlib.SupervisorStatic':'make_child_proc'(fun() -> begin S2901Res = 'Tianjiupai.PlazaServer':'start_link'(), sesterl_internal_prim:'return'('SesterlStdlib.Result':'map'((fun 'Tianjiupai.PlazaServer':'as_pid'/1), S2901Res)) end end).
'start_room_resource_server'() -> 'SesterlStdlib.SupervisorStatic':'make_child_proc'(fun() -> begin S2903Res = 'Tianjiupai.RoomResourceServer':'start_link'(), sesterl_internal_prim:'return'('SesterlStdlib.Result':'map'((fun 'Tianjiupai.RoomResourceServer':'as_pid'/1), S2903Res)) end end).
'start_user_resource_server'() -> 'SesterlStdlib.SupervisorStatic':'make_child_proc'(fun() -> begin S2905Res = 'Tianjiupai.UserResourceServer':'start_link'(), sesterl_internal_prim:'return'('SesterlStdlib.Result':'map'((fun 'Tianjiupai.UserResourceServer':'as_pid'/1), S2905Res)) end end).
'start_metrics_server'() -> 'SesterlStdlib.SupervisorStatic':'make_child_proc'(fun() -> begin S2907Res = 'Tianjiupai.MetricsServer':'start_link'(), sesterl_internal_prim:'return'('SesterlStdlib.Result':'map'((fun 'Tianjiupai.MetricsServer':'as_pid'/1), S2907Res)) end end).
'init'(_) -> begin S2909SupFlags = 'SesterlStdlib.SupervisorStatic':'make_sup_flags'(#{strategy => 'one_for_all'}), begin S2910ChildSpecs = ['SesterlStdlib.SupervisorStatic':'make_child_spec'(<<"room_server_sup"/utf8>>, {'Tianjiupai.Sup.Callback', 'start_room_server_sup', []}, #{type => 'supervisor'}) | ['SesterlStdlib.SupervisorStatic':'make_child_spec'(<<"user_server_sup"/utf8>>, {'Tianjiupai.Sup.Callback', 'start_user_server_sup', []}, #{type => 'supervisor'}) | ['SesterlStdlib.SupervisorStatic':'make_child_spec'(<<"plaza_server"/utf8>>, {'Tianjiupai.Sup.Callback', 'start_plaza_server', []}, #{type => 'worker'}) | ['SesterlStdlib.SupervisorStatic':'make_child_spec'(<<"room_resource_server"/utf8>>, {'Tianjiupai.Sup.Callback', 'start_room_resource_server', []}, #{type => 'worker'}) | ['SesterlStdlib.SupervisorStatic':'make_child_spec'(<<"user_resource_server"/utf8>>, {'Tianjiupai.Sup.Callback', 'start_user_resource_server', []}, #{type => 'worker'}) | ['SesterlStdlib.SupervisorStatic':'make_child_spec'(<<"metrics_server"/utf8>>, {'Tianjiupai.Sup.Callback', 'start_metrics_server', []}, #{type => 'worker'}) | []]]]]]], 'SesterlStdlib.SupervisorStatic':'init_ok'(S2909SupFlags, S2910ChildSpecs) end end.
