-module('Tianjiupai.PlazaServer').
-export(['start_link'/0, 'as_pid'/1, 'get_all_rooms'/0, 'update_room'/1, 'delete_room_sync'/1, 'subscribe'/2, 'unsubscribe'/1]).
'start_link'() -> 'Tianjiupai.PlazaServer.Impl':'start_link_name'(ok, {'global', ok}).
'as_pid'(S1490Proc) -> 'Tianjiupai.PlazaServer.Impl':'as_pid'(S1490Proc).
'get_all_rooms'() -> begin {'ok', S1492Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), begin S1493Res = 'Tianjiupai.PlazaServer.Impl':'call'(S1492Proc, 'get_room_list'), case S1493Res of {'ok', {'room_list_got', S1494RoomSummaries}} -> sesterl_internal_prim:'return'(S1494RoomSummaries); {'error', _} -> sesterl_internal_prim:'return'([]) end end end.
'update_room'(S1496RoomSummary) -> begin {'ok', S1497Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1497Proc, {'update_room', S1496RoomSummary}) end.
'delete_room_sync'(S1499RoomId) -> begin {'ok', S1500Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), begin S1501Res = 'Tianjiupai.PlazaServer.Impl':'call'(S1500Proc, {'delete_room_sync', S1499RoomId}), case S1501Res of {'ok', 'room_deleted'} -> begin _ = begin S3106 = 'Tianjiupai.Logger':'debug'({"room deleted (room_id: ~s)", 1}, {S1499RoomId}), S3106(<<"PlazaServer.sest">>, 301) end, sesterl_internal_prim:'return'(ok) end; {'error', S1502Err} -> begin _ = begin S3107 = 'Tianjiupai.Logger':'warning'({"delete room failed (room_id: ~s, reason: ~p)", 2}, {S1499RoomId, S1502Err}), S3107(<<"PlazaServer.sest">>, 305) end, sesterl_internal_prim:'return'(ok) end end end end.
'subscribe'(S1504UserId, S1505WsProc) -> begin {'ok', S1506Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1506Proc, {'subscribe', S1504UserId, S1505WsProc}) end.
'unsubscribe'(S1508UserId) -> begin {'ok', S1509Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1509Proc, {'unsubscribe', S1508UserId}) end.
