-module('Tianjiupai.PlazaServer').
-export(['start_link'/0, 'as_pid'/1, 'get_all_rooms'/0, 'update_room'/1, 'delete_room_sync'/1, 'subscribe'/2, 'unsubscribe'/1]).
'start_link'() -> 'Tianjiupai.PlazaServer.Impl':'start_link_name'(ok, {'global', ok}).
'as_pid'(S1504Proc) -> 'Tianjiupai.PlazaServer.Impl':'as_pid'(S1504Proc).
'get_all_rooms'() -> begin {'ok', S1506Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), begin S1507Res = 'Tianjiupai.PlazaServer.Impl':'call'(S1506Proc, 'get_room_list'), case S1507Res of {'ok', {'room_list_got', S1508RoomSummaries}} -> sesterl_internal_prim:'return'(S1508RoomSummaries); {'error', _} -> sesterl_internal_prim:'return'([]) end end end.
'update_room'(S1510RoomSummary) -> begin {'ok', S1511Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1511Proc, {'update_room', S1510RoomSummary}) end.
'delete_room_sync'(S1513RoomId) -> begin {'ok', S1514Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), begin S1515Res = 'Tianjiupai.PlazaServer.Impl':'call'(S1514Proc, {'delete_room_sync', S1513RoomId}), case S1515Res of {'ok', 'room_deleted'} -> begin _ = begin S3219 = 'Tianjiupai.Logger':'debug'({"room deleted (room_id: ~s)", 1}, {S1513RoomId}), S3219(<<"PlazaServer.sest">>, 301) end, sesterl_internal_prim:'return'(ok) end; {'error', S1516Err} -> begin _ = begin S3220 = 'Tianjiupai.Logger':'warning'({"delete room failed (room_id: ~s, reason: ~p)", 2}, {S1513RoomId, S1516Err}), S3220(<<"PlazaServer.sest">>, 305) end, sesterl_internal_prim:'return'(ok) end end end end.
'subscribe'(S1518UserId, S1519WsProc) -> begin {'ok', S1520Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1520Proc, {'subscribe', S1518UserId, S1519WsProc}) end.
'unsubscribe'(S1522UserId) -> begin {'ok', S1523Proc} = 'Tianjiupai.PlazaServer.Impl':'where_is_global'(ok), 'Tianjiupai.PlazaServer.Impl':'cast'(S1523Proc, {'unsubscribe', S1522UserId}) end.
